# Generated by Django 6.1 on 2026-08-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado (Asiste)'), ('RECHAZADO', 'Rechazado (No asiste)')], default='PENDIENTE', max_length=20, verbose_name='Estado de confirmación')),
                ('acompanantes', models.PositiveIntegerField(default=0, verbose_name='Número de acompañantes')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje o dedicatoria')),
                ('fecha_respuesta', models.DateTimeField(auto_now=True, verbose_name='Fecha de respuesta')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'ordering': ['-fecha_respuesta'],
            },
        ),
    ]
