# Generated by Django 6.1 on 2026-08-30 19:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_invitado', models.CharField(max_length=150, verbose_name='Nombre del Invitado')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token Único')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('activa', models.BooleanField(default=True, verbose_name='Invitación Activa')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado (Asiste)'), ('RECHAZADO', 'Rechazado (No asiste)')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('lleva_acompanantes', models.BooleanField(default=False, verbose_name='¿Lleva acompañantes?')),
                ('cantidad_acompanantes', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Acompañantes')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje o Dedicatoria')),
                ('fecha_respuesta', models.DateTimeField(auto_now=True, verbose_name='Fecha de Respuesta')),
                ('invitacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='core.invitacion', verbose_name='Invitación')),
            ],
            options={
                'verbose_name': 'Respuesta RSVP',
                'verbose_name_plural': 'Respuestas RSVP',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.DeleteModel(
            name='Invitado',
        ),
    ]
