# Generated by Django 6.1 on 2026-09-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invitacion_respuestarsvp_delete_invitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_evento', models.CharField(default='Fiesta de Graduación', max_length=200)),
                ('fecha', models.DateField(verbose_name='Fecha del evento')),
                ('hora', models.TimeField(verbose_name='Hora del evento')),
                ('lugar', models.CharField(max_length=255, verbose_name='Lugar / Dirección')),
                ('organizador', models.CharField(default='Instituto Ameyali', max_length=150, verbose_name='Nombre del organizador/instituto')),
            ],
            options={
                'verbose_name': 'Configuración del Evento',
                'verbose_name_plural': 'Configuración del Evento',
            },
        ),
    ]
